[Do_not_merge]add new lookup plugin json_template
ansible-network/network-engine pull request #39
Opened 2018-04-20 08:05 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>
Fixes https://github.com/ansible-network/network-engine/issues/32

2018-04-20 10:29 UTC, privateip requested changes

2018-04-20 10:29 UTC, privateip commented on lookup_plugins/json_template.py
> +try:
You can import display from `ansible.plugins.lookup`

2018-04-20 10:29 UTC, privateip commented on lookup_plugins/json_template.py
> +        for term in to_list(terms[0]):
This should only use a single path not a list of paths.  Change `to_list(terms[0])` to `terms[0]` and remove the `for` loop

2018-04-20 10:29 UTC, privateip commented on lookup_plugins/json_template.py
> +                        ret.append(json.load(f))
This needs to pass through `network_engine.plugins.template.json_template`

2018-04-23 11:35 UTC, privateip approved these changes

2018-04-24 15:36 UTC, trishnaguha commented
This needs to be cherry-picked to devel.

2018-04-24 15:36 UTC, merged