How to use doc
ansible-network/network-engine pull request #52
Opened 2018-04-27 05:35 UTC by trishnaguha

2018-04-27 07:14 UTC, gundalow reviewed
Looks great. Just a few minor formatting suggestions.

I wonder if it would be worth adding a link to the module's source, which is where we describe the other module options?

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/text_parser.md
> +  - name: Genereta interface facts as JSON
Genereta -> Generate

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/text_parser.md
> +# text_paser
I wonder if it would be worth linking to the module's source, so they can see the other options available, such as `dir`?

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/text_parser.md
> +  - name: Genereta interface facts as JSON
suggestion: Generate interface facts as JSON from a previously generated text file

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/text_parser.md
> +The `file` parameter for `text_parser` contains rules to parse text.
Please add a single newline between heading and text

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/text_parser.md
> +Directives documentation is available [Here](https://github.com/ansible-network/network-engine/blob/devel/docs/directives/parser_directives.md).
suggestion: Directives documentation is available in [parser_directives.md](https://github.com/ansible-network/network-engine/blob/devel/docs/directives/parser_directives.md).

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/textfsm.md
> +  - name: Genereta interface facts as JSON
Same as text_parser comment

2018-04-27 07:14 UTC, gundalow commented on docs/user_guide/textfsm.md
> +The `file` parameter for `textfsm` contains the standard textfsm rules.
Newline

2018-04-27 07:23 UTC, trishnaguha commented on docs/user_guide/text_parser.md
> +  - name: Genereta interface facts as JSON
The text file is static here, isn't generated.

2018-04-27 07:45 UTC, gundalow approved these changes
Thanks!

2018-04-27 11:16 UTC, privateip requested changes
Need to fix the examples as they wont work as is

2018-05-10 15:42 UTC, acozine commented
Closing. This work is incorporated in #68.

2018-05-10 15:42 UTC, closed without merging