Fix StringIO to work with Python3 in addition to Python2
ansible-network/network-engine pull request #53
Opened 2018-04-28 20:13 UTC by jmcgill298

Currently import of StringIO raises an exception when using Python3.6. This should fix the bug, and is the general practice with modules in ansible-core.

2018-04-30 13:37 UTC, trishnaguha requested changes

2018-04-30 13:37 UTC, trishnaguha commented on action_plugins/textfsm.py
> +from io import StringIO
StringIO should be imported from ansible.module_utils.six otherwise this will break Python2.x

2018-04-30 18:04 UTC, jmcgill298 commented
I don't mind changing it, however I have not had issues with my current PR's implementation using Python2.6 and Python2.7 (Ansible's only Python2 supported versions). Since I cannot produce an issue with your concerns, and I believe your suggestion is an issue with releases earlier than Python2.6(see below), I want to validate that this implementation follows Ansible's current standards. Here is a list of files and their corresponding import.

`from io import StringIO`:
  - ansible/lib/ansible/template/__init__.py
  - ansible/lib/ansible/executor/module_common.py
  - ansible/lib/ansible/plugins/lookup/ini.py
  - ansible/test/units/plugins/connection/test_network_cli.py
  - ansible/test/units/parsing/yaml/test_dumper.py
  - ansible/test/units/executor/module_common/test_recursive_finder.py
  - ansible/test/units/plugins/connection/test_ssh.py
  - ansible/test/units/plugins/connection/test_connection.py
  - ansible/test/units/parsing/vault/test_vault.py
  - ansible/test/units/plugins/connection/test_netconf.py
  - ansible/test/units/mock/procenv.py

`from ansible.module_utils.six.moves import StringIO`:
  - ansible/bin/ansible-connection
  - ansible/contrib/inventory/vagrant.py
  - ansible/lib/ansible/module_utils/facts/system/local.py

`from ansible.module_utils.six import StringIO`:
  - ansible/lib/ansible/plugins/netconf/iosxr.py
  - ansible/test/units/test_constants.py
  - ansible/test/units/module_utils/urls/test_fetch_url.py
  - ansible/test/units/module_utils/urls/test_RedirectHandlerFactory.py


`from ansible.module_utils.six.moves import cStringIO as StringIO`:
  - ansible/lib/ansible/modules/web_infrastructure/ansible_tower/tower_job_wait.py

`ansible/lib/ansible/executor/module_common.py` indicates StringIO.StringIO was used for versions prior to Python2.6 (these versions are not longer supported):
```
try:
    # Python-2.6+
    from io import BytesIO as IOStream
except ImportError:
    # Python < 2.6
    from StringIO import StringIO as IOStream
```

As you can see, there is some discrepancy on how this should be imported, with my current implementation being the most utilized. Please confirm that your suggestion is the Ansible standard and I will adjust.

2018-05-02 11:13 UTC, trishnaguha commented
@jmcgill298 Python's official 2.7.x documentation states:
` Under Python 2.x, this is proposed as an alternative to the built-in file object, but in Python 3.x it is the default interface to access files and streams.
Note Since this module has been designed primarily for Python 3.x` https://docs.python.org/2.7/library/io.html

which is why in we handle PY2, PY3 imports with [module_utils.six](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/six/__init__.py#L629-L669) 
where for PY2 we import from `StringIO` and PY3 we import from `io`.

2018-05-10 03:34 UTC, trishnaguha approved these changes

2018-05-10 03:34 UTC, merged