Add config_diff lookup plugin
ansible-network/network-engine pull request #88
Opened 2018-06-04 09:39 UTC by ganeshrn

*  Add config diff lookup plugin
*  Add integration test for config_diff
*  Doc update

2018-06-05 05:24 UTC, trishnaguha commented
recheck

2018-06-06 03:22 UTC, trishnaguha commented on lookup_plugins/config_diff.py
> +version_added: "2.6"
shouldn't this be 2.5?

2018-06-06 03:23 UTC, trishnaguha requested changes
please remove the retry file from tests/

2018-06-06 05:58 UTC, ganeshrn commented on lookup_plugins/config_diff.py
> +version_added: "2.6"
fixed

2018-06-06 05:59 UTC, ganeshrn commented
@trishnaguha Fixed review comments

2018-06-06 07:01 UTC, trishnaguha approved these changes

2018-06-06 07:01 UTC, merged