Templating the regex sent to the parser to allow us to use ansible va…
ansible-network/network-engine pull request #97
Opened 2018-06-19 17:55 UTC by jmighion

…rs in the regex string

This allows use of vars and filters inside the regex string.

Example. Looking for an interface name inside a different output where that interface name changes because this `pattern_match` is ran inside a loop. : 
```yaml
- name: match name for old ios versions
  pattern_match:
    regex: "^({{ (item | regex_search('System Name(?: -|:) (\\S+)', '\\1') | first).split('.')[0] }}.+$)"
    content: "{{ detail }}"
```

2018-06-25 13:05 UTC, privateip commented
LGTM

2018-06-25 13:05 UTC, privateip approved these changes

2018-06-25 13:18 UTC, ganeshrn requested changes
Please add some documentation with example aorund this in https://github.com/ansible-network/network-engine/blob/devel/docs/directives/parser_directives.md

2018-06-26 07:51 UTC, ganeshrn approved these changes

2018-06-26 07:51 UTC, ganeshrn commented
@jmighion Thank you!

2018-06-26 07:51 UTC, merged